# Verilerin Düzenlenmesi ve Birleştirilmesi

In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv('Seasons_Stats.csv') #istatistiklerin olduğu data
salary = pd.read_csv("NBA_season1718_salary.csv") #maaşların olduğu data

In [3]:
stats.columns

Index(['Unnamed: 0', 'Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP',
       'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%',
       'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2',
       'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
       '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [4]:
#İmzalanan kontratla yani maaşla etkili olabileceğini düşündüğüm, incelenecek spesifik veriler: (+ : pozitif özellik , - : negatif özellik )
#MPG = Minutes Played per Game (Maç başına oynanan süre)(+)
#PPG = Points per Game (Maç başına atılan sayı)(+)
#TOPG = Turnover per Game (Maç başına kaybedilen top)(-)
#PFG = Personal Fouls per Game (Maç başına yapılan bireysel fauller)(-)

#PER = Player Efficiency Rating (Oyuncu verimlilik puanı)(+)
#AGE = Yaş, oyuncu genç ise (+), görece yaşlı ise (-) olduğu düşünüldü

#Veri setinde olmayan spesifik mpg, ppg, topg, pfg verileri hesaplanmalı.

#mpg = mp(minutes played)/g(games played)

#ppg = pts(points)/g(games played)

#topg = tov(turnovers)/g

#pfg = pf(personal fouls)/g

In [6]:
#Gerekli hesaplamaları yapıp dataframe'e ekleme
specific_calc = ['MPG','PPG','TOPG','PFG']
calc_from = ['MP','PTS','TOV','PF']

for a,b in zip (specific_calc,calc_from):
    stats[a] = stats[b] / stats['G']

In [7]:
#veriler 2017 sezonu sonrasını içermiyor, maaş verileriyle merge etmek için
#stats['Year']>= 2016 ve stats['Year']<2017 almak yeterli
#böylelikle 2016-2017 sezonu istatistikleri oyuncuların bir sonraki sene olan 2017-2018 sezonu maaşlarına 
#nasıl etki etmiş bakabileceğiz
stats.tail(10)

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,AST,STL,BLK,TOV,PF,PTS,MPG,PPG,TOPG,PFG
24681,24681,2017.0,Delon Wright,PG,24.0,TOR,27.0,0.0,446.0,15.0,...,57.0,27.0,11.0,25.0,31.0,150.0,16.518519,5.555556,0.925926,1.148148
24682,24682,2017.0,James Young,SG,21.0,BOS,29.0,0.0,220.0,10.0,...,4.0,10.0,2.0,4.0,15.0,68.0,7.586207,2.344828,0.137931,0.517241
24683,24683,2017.0,Joe Young,PG,24.0,IND,33.0,0.0,135.0,11.4,...,15.0,4.0,0.0,5.0,5.0,68.0,4.090909,2.060606,0.151515,0.151515
24684,24684,2017.0,Nick Young,SG,31.0,LAL,60.0,60.0,1556.0,14.1,...,58.0,37.0,14.0,36.0,137.0,791.0,25.933333,13.183333,0.600000,2.283333
24685,24685,2017.0,Thaddeus Young,PF,28.0,IND,74.0,74.0,2237.0,14.9,...,122.0,114.0,30.0,96.0,135.0,814.0,30.229730,11.000000,1.297297,1.824324
24686,24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,...,99.0,62.0,58.0,65.0,189.0,639.0,27.822581,10.306452,1.048387,3.048387
24687,24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,...,42.0,7.0,21.0,20.0,61.0,178.0,10.294118,3.490196,0.392157,1.196078
24688,24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,...,4.0,2.0,5.0,3.0,17.0,23.0,5.684211,1.210526,0.157895,0.894737
24689,24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,...,36.0,15.0,16.0,40.0,78.0,240.0,19.159091,5.454545,0.909091,1.772727
24690,24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,...,30.0,14.0,33.0,30.0,66.0,284.0,16.026316,7.473684,0.789474,1.736842

In [8]:
#'player' ve 'season17_18' sütunları stats dataframe'i ile merge edilecek 
salary.columns

Index(['Unnamed: 0', 'Player', 'Tm', 'season17_18'], dtype='object')

In [9]:
import warnings
warnings.filterwarnings('ignore')

In [10]:
#stats datasının sadece 2016 ve sonrasını + 2017 öncesini aldık, çünkü salary datası sadece 2017-2018
#sezonunu kapsıyor, bu durumda sadece 2016 sonrasında ve 2017 öncesinde hem salary hem stats datasında bulunan
#oyuncuların verileri merge edilecek
stats = stats[stats['Year']>=2016]
stats = stats[stats['Year']<2017]
#gerekli sütunları alıyoruz
stats = stats[['Player','Year',"Age",'MPG','PPG','PER','TOPG','PFG']]
stats.columns

Index(['Player', 'Year', 'Age', 'MPG', 'PPG', 'PER', 'TOPG', 'PFG'], dtype='object')

# Merge işlemi ve sonrasında düzenlemeler

In [11]:
#stats ve salary df'ini birleştirme
nba_salary_and_stats = pd.merge(stats , salary)
nba_salary_and_stats.head(10)

,Player,Year,Age,MPG,PPG,PER,TOPG,PFG,Unnamed: 0,Tm,season17_18
0,Quincy Acy,2016.0,25.0,14.847458,5.203390,14.7,0.457627,1.745763,350,BRK,1709538.0
1,Steven Adams,2016.0,22.0,25.175000,7.950000,15.5,1.050000,2.787500,32,OKC,22471910.0
2,Arron Afflalo,2016.0,30.0,33.394366,12.802817,10.9,1.154930,2.000000,291,ORL,2328652.0
3,Arron Afflalo,2016.0,30.0,33.394366,12.802817,10.9,1.154930,2.000000,378,SAC,1500000.0
4,Alexis Ajinca,2016.0,27.0,14.593220,5.966102,13.8,0.915254,2.271186,206,NOP,4961798.0
5,Cole Aldrich,2016.0,27.0,13.333333,5.466667,21.3,1.066667,2.316667,155,MIN,7300000.0
6,LaMarcus Aldridge,2016.0,30.0,30.554054,17.986486,22.4,1.337838,2.040541,36,SAS,21461010.0
7,Tony Allen,2016.0,34.0,25.312500,8.359375,12.9,1.218750,2.734375,323,CHI,2116955.0
8,Al-Farouq Aminu,2016.0,25.0,28.548780,10.231707,12.7,1.463415,2.085366,154,POR,7319035.0
9,Justin Anderson,2016.0,22.0,11.763636,3.781818,12.3,0.436364,0.818182,357,PHI,1579440.0

In [12]:
nba_salary_and_stats.drop_duplicates(subset=['Player'], keep='first',inplace=True)
#çift verilerden kurtulmak için

In [13]:
nba_salary_and_stats.drop(columns=['Unnamed: 0', 'Tm'], axis=1, inplace=True)
#gereksiz sütunlardan kurtulma

In [14]:
#yıl, maaş sütununu yeniden adlandırma ve maaşı birimi milyona çevirme
nba_salary_and_stats.rename(columns = {'Year':'Stats_from'}, inplace = True)
nba_salary_and_stats.rename(columns = {'season17_18':'2017_2018 Salary'}, inplace = True)
nba_salary_and_stats['2017_2018 Salary'] = nba_salary_and_stats[['2017_2018 Salary']].applymap(lambda line: line/1000000)

In [18]:
#merge başarılı ve null değer gözükmüyor 
nba_salary_and_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 345 entries, 0 to 429
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            345 non-null    object
 1   Stats_from        345 non-null    float64
 2   Age               345 non-null    float64
 3   MPG               345 non-null    float64
 4   PPG               345 non-null    float64
 5   PER               345 non-null    float64
 6   TOPG              345 non-null    float64
 7   PFG               345 non-null    float64
 8   2017_2018 Salary  345 non-null    float64
dtypes: float64(8), object(1)
memory usage: 27.0+ KB

In [19]:
nba_salary_and_stats.head(10)

,Player,Stats_from,Age,MPG,PPG,PER,TOPG,PFG,2017_2018 Salary
0,Quincy Acy,2016.0,25.0,14.847458,5.203390,14.7,0.457627,1.745763,1.709538
1,Steven Adams,2016.0,22.0,25.175000,7.950000,15.5,1.050000,2.787500,22.471910
2,Arron Afflalo,2016.0,30.0,33.394366,12.802817,10.9,1.154930,2.000000,2.328652
4,Alexis Ajinca,2016.0,27.0,14.593220,5.966102,13.8,0.915254,2.271186,4.961798
5,Cole Aldrich,2016.0,27.0,13.333333,5.466667,21.3,1.066667,2.316667,7.300000
6,LaMarcus Aldridge,2016.0,30.0,30.554054,17.986486,22.4,1.337838,2.040541,21.461010
7,Tony Allen,2016.0,34.0,25.312500,8.359375,12.9,1.218750,2.734375,2.116955
8,Al-Farouq Aminu,2016.0,25.0,28.548780,10.231707,12.7,1.463415,2.085366,7.319035
9,Justin Anderson,2016.0,22.0,11.763636,3.781818,12.3,0.436364,0.818182,1.579440
10,Kyle Anderson,2016.0,22.0,15.961538,4.487179,12.9,0.756410,1.243590,2.151704

In [20]:
nba_salary_and_stats.tail(10)

,Player,Stats_from,Age,MPG,PPG,PER,TOPG,PFG,2017_2018 Salary
420,Marvin Williams,2016.0,29.0,28.864198,11.703704,16.8,0.765432,1.641975,13.168750
421,Justise Winslow,2016.0,19.0,28.615385,6.435897,8.4,1.217949,2.358974,2.705040
422,Jeff Withey,2016.0,25.0,12.901961,4.254902,17.7,0.549020,1.470588,1.577320
423,Brandan Wright,2016.0,28.0,17.666667,6.916667,18.3,0.833333,1.750000,5.179760
424,Delon Wright,2016.0,23.0,8.481481,3.814815,17.8,0.592593,0.259259,1.645200
425,Joe Young,2016.0,23.0,9.365854,3.756098,9.9,0.804878,0.731707,1.471382
426,Nick Young,2016.0,30.0,19.129630,7.259259,9.1,0.555556,0.925926,5.192000
427,Thaddeus Young,2016.0,27.0,32.972603,15.095890,17.5,1.863014,2.493151,14.796348
428,Cody Zeller,2016.0,23.0,24.301370,8.739726,16.1,0.931507,2.794521,12.584270
429,Tyler Zeller,2016.0,26.0,11.833333,6.066667,15.4,0.766667,1.616667,1.709538

In [21]:
#merge sonrası bozulan indexleri sıfırladık
nba_salary_and_stats.reset_index(inplace=True)

In [22]:
nba_salary_and_stats.tail(10)

,index,Player,Stats_from,Age,MPG,PPG,PER,TOPG,PFG,2017_2018 Salary
335,420,Marvin Williams,2016.0,29.0,28.864198,11.703704,16.8,0.765432,1.641975,13.168750
336,421,Justise Winslow,2016.0,19.0,28.615385,6.435897,8.4,1.217949,2.358974,2.705040
337,422,Jeff Withey,2016.0,25.0,12.901961,4.254902,17.7,0.549020,1.470588,1.577320
338,423,Brandan Wright,2016.0,28.0,17.666667,6.916667,18.3,0.833333,1.750000,5.179760
339,424,Delon Wright,2016.0,23.0,8.481481,3.814815,17.8,0.592593,0.259259,1.645200
340,425,Joe Young,2016.0,23.0,9.365854,3.756098,9.9,0.804878,0.731707,1.471382
341,426,Nick Young,2016.0,30.0,19.129630,7.259259,9.1,0.555556,0.925926,5.192000
342,427,Thaddeus Young,2016.0,27.0,32.972603,15.095890,17.5,1.863014,2.493151,14.796348
343,428,Cody Zeller,2016.0,23.0,24.301370,8.739726,16.1,0.931507,2.794521,12.584270
344,429,Tyler Zeller,2016.0,26.0,11.833333,6.066667,15.4,0.766667,1.616667,1.709538

In [23]:
nba_salary_and_stats.drop(['index'],axis=1,inplace=True)
#index sıfırlama sonrası eski index sütununu sildik

In [24]:
nba_salary_and_stats

,Player,Stats_from,Age,MPG,PPG,PER,TOPG,PFG,2017_2018 Salary
0,Quincy Acy,2016.0,25.0,14.847458,5.203390,14.7,0.457627,1.745763,1.709538
1,Steven Adams,2016.0,22.0,25.175000,7.950000,15.5,1.050000,2.787500,22.471910
2,Arron Afflalo,2016.0,30.0,33.394366,12.802817,10.9,1.154930,2.000000,2.328652
3,Alexis Ajinca,2016.0,27.0,14.593220,5.966102,13.8,0.915254,2.271186,4.961798
4,Cole Aldrich,2016.0,27.0,13.333333,5.466667,21.3,1.066667,2.316667,7.300000
...,...,...,...,...,...,...,...,...,...
340,Joe Young,2016.0,23.0,9.365854,3.756098,9.9,0.804878,0.731707,1.471382
341,Nick Young,2016.0,30.0,19.129630,7.259259,9.1,0.555556,0.925926,5.192000
342,Thaddeus Young,2016.0,27.0,32.972603,15.095890,17.5,1.863014,2.493151,14.796348
343,Cody Zeller,2016.0,23.0,24.301370,8.739726,16.1,0.931507,2.794521,12.584270
344,Tyler Zeller,2016.0,26.0,11.833333,6.066667,15.4,0.766667,1.616667,1.709538

In [25]:
#son oluşturduğumuz gerekli bilgileri içeren nba_salary_and_stats dataframe'ini tahmin çalışmaları yapmak üzere kaydetme 
nba_salary_and_stats.to_csv("nba_stats_salaries_2017_2018.csv", index=False)